<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>Behnam Hadipanah</Authors>
    <PackageIcon>icon.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Kootam.AutoMap.Abstractions" Version="1.0.0" />
    <PackageReference Include="Mapster" Version="10.0.7" />
    <PackageReference Include="Mapster.DependencyInjection" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.8" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.8" />
  </ItemGroup>


  <ItemGroup>
    <None Include="icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
