<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageIcon>icon.png</PackageIcon>
        <Authors>Behnam Hadipanah</Authors>
    </PropertyGroup>


    <ItemGroup>
        <PackageReference Include="Kootam.UserManagement.Abstractions" Version="1.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.11" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.10" />
        <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.10" />
        <PackageReference Include="Serilog" Version="4.4.0" />
        <PackageReference Include="Serilog.Enrichers.Span" Version="3.1.0" />
        <PackageReference Include="Serilog.Exceptions" Version="8.4.0" />
    </ItemGroup>

    <ItemGroup>
        <None Include="icon.png" Pack="true" PackagePath="\" />
    </ItemGroup>
</Project>
