<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>




  <ItemGroup>
    <None Include="obj\Debug\net10.0\Kootam.Framework.Extensions.Translator.AssemblyInfoInputs.cache" />
    <None Include="obj\Debug\net10.0\Kootam.Framework.Extensions.Translator.assets.cache" />
    <None Include="obj\Debug\net10.0\Kootam.Framework.Extensions.Translator.csproj.AssemblyReference.cache" />
    <None Include="obj\Debug\net10.0\Kootam.Framework.Extensions.Translator.GeneratedMSBuildEditorConfig.editorconfig" />
    <None Include="obj\Debug\net10.0\Kootam.Framework.Extensions.Translators.AssemblyInfoInputs.cache" />
    <None Include="obj\Debug\net10.0\Kootam.Framework.Extensions.Translators.assets.cache" />
    <None Include="obj\Debug\net10.0\Kootam.Framework.Extensions.Translators.csproj.AssemblyReference.cache" />
    <None Include="obj\Debug\net10.0\Kootam.Framework.Extensions.Translators.csproj.CoreCompileInputs.cache" />
    <None Include="obj\Debug\net10.0\Kootam.Framework.Extensions.Translators.GeneratedMSBuildEditorConfig.editorconfig" />
    <None Include="obj\Debug\net10.0\Kootam.Framework.Translator.Database.AssemblyInfoInputs.cache" />
    <None Include="obj\Debug\net10.0\Kootam.Framework.Translator.Database.assets.cache" />
    <None Include="obj\Debug\net10.0\Kootam.Framework.Translator.Database.GeneratedMSBuildEditorConfig.editorconfig" />
    <None Include="obj\Kootam.Framework.Extensions.Translator.csproj.nuget.g.props" />
    <None Include="obj\Kootam.Framework.Extensions.Translator.csproj.nuget.g.targets" />
    <None Include="obj\Kootam.Framework.Extensions.Translators.csproj.nuget.g.props" />
    <None Include="obj\Kootam.Framework.Extensions.Translators.csproj.nuget.g.targets" />
    <None Include="obj\Kootam.Framework.Translator.Database.csproj.nuget.g.props" />
    <None Include="obj\Kootam.Framework.Translator.Database.csproj.nuget.g.targets" />
    <None Include="obj\project.nuget.cache" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Abstractions\Kootam.Framework.Translator.Abstractions\Kootam.Framework.Translator.Abstractions.csproj" />
  </ItemGroup>

</Project>
