<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<Compile Update="Repository\RedisRepository.Hash.cs">
			<DependentUpon>RedisRepository.cs</DependentUpon>
		</Compile>
		<Compile Update="Repository\RedisRepository.Collections.cs">
			<DependentUpon>RedisRepository.cs</DependentUpon>
		</Compile>
		<Compile Update="Repository\RedisRepository.Advanced.cs">
			<DependentUpon>RedisRepository.cs</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.3" />
    
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="StackExchange.Redis" Version="2.11.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Abstractions\Kootam.Framework.Caching.Abstractions\Kootam.Framework.Caching.Abstractions.csproj" />
  </ItemGroup>

</Project>
